### ISSUE TITLE
Datenpunkt husqvarna-automower.0.XXXXXXX.planner.nextStartTimestamp

### ISSUE THREAD

**Issue by intruder7777** [ice987987/ioBroker.husqvarna-automower#10]
Auch von mir nochmal Danke für den Adapter...

Aktuell gibt es bei mir noch ein Problem mit dem oben genannten Datenpunkt.
Starte ich den Mäher mit einem Schedule ( setze den Datenpunkt husqvarna-automower.0.XXXXXX.ACTIONS.RESUMESCHEDULE auf true), schreibt er den korrekten Wert in den Datenpunkt.
Breche ich aber alles ab in dem ich ihn wieder auf parken schicke (husqvarna-automower.0.XXXXXXX.ACTIONS.PARKUNTILFURTHERNOTICE auf true), führt er dieses zwar korrekt aus aber er setzt den "nextStartTimestamp" nicht wieder auf 0. es bleibt der letzte timestamp drinn stehen obwohl der Mäher nicht mehr mähen geht.

**Comment by ice987987** [comment]
Das müsste ich mir mal genau anschauen. Wenn der Adapter auf log-level "debug" steht: welche Werte werden von der API für den Wert "nextStartTimestamp" geschickt?

gem [API](https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/swagger):
_description: Information about the planner
nextStartTimestamp
Timestamp for the next auto start in milliseconds since 1970-01-01T00:00:00 in local time. If the mower is charging then the value is the estimated time when it will be leaving the charging station. **If the value is 0 then the mower should start now**. NOTE! This timestamp is in local time for the mower and is coming directly from the mower._

**Comment by intruder7777** [comment]
dies wird von der api nach einem restart geschickt

,"battery":{"batteryPercent":100},"mower":{"mode":"HOME","activity":"PARKED_IN_CS","state":"RESTRICTED","errorCode":0,"errorCodeTimestamp":0},"calendar":{"tasks":[{"start":540,"duration":780,"monday":true,"tuesday":false,"wednesday":false,"thursday":false,"friday":true,"saturday":true,"sunday":true}]},"planner":{"nextStartTimestamp":0,"override":{"action":"NO_SOURCE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1650228018740},"positions":

und das steht immer noch im Datenpunkt

![image](https://user-images.githubusercontent.com/45670139/163731504-dc8a3e6c-adbd-48dc-8a92-5b205e516ec7.png)

**Comment by ice987987** [comment]
"planner":{"nextStartTimestamp":0 -> DP noch mit Datum. Muss ich anschauen.

**Comment by ice987987** [comment]
Könntest du ggf. die neueste Version ausprobieren und prüfen?

**Comment by intruder7777** [comment]
auf die schnelle getestet.....und funktioniert erstmal... danke dir
